### ISSUE TITLE
New Geoguessr

### ISSUE THREAD

**Issue by Pyewackets** [fabrice404/geoguessr-timer#49]
I use Firefox and since this new Geoguessr came out I can't get the timer to show up. Any chance you could tweak it please, I really miss trying to beat my best times.

**Comment by fabrice404** [comment]
Hi! Sorry I've just seen your message, I can try to update it if you still want it. Let me know 😃

**Comment by Pyewackets** [comment]
Hi thanks for asking....yes please I'd love to be able to use this again. Since I wrote though I've sort of migrated over to Chrome although I can still use Firefox.

**Comment by fabrice404** [comment]
It should be compatible with both Firefox and Chrome. I've started to work on it, but as they have completely changed the website, it will take a few days for me to update it.

**Comment by Pyewackets** [comment]
Thats great news - thank you for your time

**Comment by fabrice404** [comment]
The new version is available! Please create a new issue if you find any
