### ISSUE TITLE
Not saving scores

### ISSUE THREAD

**Issue by Pyewackets** [fabrice404/geoguessr-timer#52]
Just had a chance to finally start using this and unfortunately it does not record your personal best scores like it used to, when you play the same map again it just comes up with blank fields as if its a new map.

**Comment by fabrice404** [comment]
That's correct. I've just tested it and it doesn't save, it was working last time so they may have changed something on the website. Thanks for letting me know, I didn't spot it because I play only country streak for now, but I'll try to fix it quickly.

**Comment by fabrice404** [comment]
I've found the issue, they've changed the button at the end of the game. 
I'm adding a feature for country streak mode and I'll publish a new version.

**Comment by Pyewackets** [comment]
great thanks

**Comment by fabrice404** [comment]
The new version 1.0.1 has been approved last night on both Chrome and Firefox, feel free to close the issue once you've tested it 🙂

**Comment by Pyewackets** [comment]
All working , thank you again
